context.modules = [
{   name = libpipewire-module-loopback
    args = {
        node.name = "sink"
        capture.props = {
            media.class = "Audio/Sink"
        }
    }
}
{   name = libpipewire-module-loopback
    args = {
        node.name = "source"
        capture.props = {
            media.class = "Audio/Sink"
        }
        playback.props = {
            media.class = "Audio/Source"
            audio.position = [ FL FR ]
        }
    }
}
]
